yardim harita update
acikkaynak/deprem-io-frontend pull request #110
Opened 2023-02-10 20:36 UTC by karasakalmt

2023-02-10 22:19 UTC, yusufdeepwork commented
Selam. Ayrıca deprem.io haritasına tıklayınca enkaz altındakilerin listesine gitmeli, bunu ekleyebilir misin çünkü deprem.io'da öyle yapılmış. Ayrıca deprem.io'da harita resminin altında haritaya git denilmiş ama bu nice to have bence
<img width="474" alt="image" src="https://user-images.githubusercontent.com/57027351/218209420-d1f6a847-7aee-4995-a045-6c35ba61f6bb.png">

2023-02-10 22:20 UTC, yusufdeepwork requested changes
Kod okay ama pr yorumuna eklediğim düzeltmeyi yaparsan güzel olur

2023-02-10 22:30 UTC, karasakalmt commented
bos sayfa donuyor bende dolu sayfa donuyorsa updateleyelim eger dolu bir sayfa donuyorsa su an eklemeye gerek yok

2023-02-10 22:31 UTC, karasakalmt commented
bizde o feature yok sanirim bn de eklenmis olmasi lazim baska issue nun problemi o

2023-02-10 22:46 UTC, yusufdeepwork commented
> bizde o feature yok sanirim bn de eklenmis olmasi lazim baska issue nun problemi o

https://dev.thechainlist.io/yardim-istekleri/enkaz.html şu sayfaya yönlendirme yapması gerekmiyor mu

2023-02-11 00:21 UTC, yusufdeepwork approved these changes
deprem.io ya enkazda kalanlar listesi linkini ekledim

2023-02-11 00:21 UTC, merged