#78 kurumlara bagis yap
acikkaynak/deprem-io-frontend pull request #79
Opened 2023-02-09 23:44 UTC by anilcanboga

Kurumlara bağış yap sayfasına yeni linkler eklenmesi #78
Amazon
N11
Çiçeksepeti
üzerinden bağış yapılması için linkler eklendi.

2023-02-09 23:49 UTC, zafergurel requested changes
Tüm eklemeleri, alfabetik sıraya uygun şekilde düzenler misiniz?

2023-02-09 23:49 UTC, zafergurel commented on yardim-sagla/bagis.html
> +                                        <p>Çiçeksepetin'den Bağış Yap</p>
```suggestion
                                        <p>Çiçeksepeti'nden Bağış Yap</p>
```

2023-02-10 00:09 UTC, anilcanboga commented on yardim-sagla/bagis.html
> +                                        <p>Çiçeksepetin'den Bağış Yap</p>
düzenlendi.

2023-02-10 00:28 UTC, zafergurel commented on yardim-sagla/bagis.html
> +                                        <p>Çiçeksepetin'den Bağış Yap</p>
Elinize sağlık.
İki şey var:
- Çiçeksepetin'den -> Çiçeksepeti'nden olacaktı. 
- Linkler de alfabetik sıralamada olursa tamamdır.

2023-02-10 00:34 UTC, anilcanboga commented on yardim-sagla/bagis.html
> +                                        <p>Çiçeksepetin'den Bağış Yap</p>
Evet o yazım yanlışını düzelttim. Tüm linkleri de alfabetik sıraya göre düzenledim.

2023-02-10 00:37 UTC, zafergurel approved these changes
Bu tamamdır. Elinize sağlık.

2023-02-10 00:37 UTC, merged