detay sayfasinda arac durumu backend baglantisi eklendi
acikkaynak/deprem-io-frontend pull request #96
Opened 2023-02-10 12:17 UTC by fatihozdil

2023-02-10 19:32 UTC, karasakalmt requested changes

2023-02-10 19:32 UTC, karasakalmt commented on yardim-detay/detay.html
> +                                <input type="radio" id="araciYok" name="arac" value="Araci Yok">
Araci Yok diye bir value atmayalim var ve yok yazalim 239 da

2023-02-11 01:32 UTC, fatihozdil commented on yardim-detay/detay.html
> +                                <input type="radio" id="araciYok" name="arac" value="Araci Yok">
request atmadigi icin db ye bir yazma islemi gerceklesmiyor ancak yine de degistirdim

2023-02-11 01:36 UTC, mehmetik approved these changes
LGTM!

2023-02-11 01:39 UTC, merged